export const rollData = {
  d20Rolls: [
    { roller: "DM (Kevin) (GM)", result: "4" },
    { roller: "Nate", result: "12" },
    { roller: "Nate", result: "15" },
    { roller: "Nate", result: "14" },
    { roller: "Nate", result: "7" },
    { roller: "Nate", result: "8" },
    { roller: "Nate", result: "2" },
    { roller: "Dorkus", result: "20" },
    { roller: "Dorkus", result: "19" },
    { roller: "Nate", result: "2" },
    { roller: "Nate", result: "11" },
    { roller: "Nate", result: "18" },
    { roller: "Nate", result: "14" },
    { roller: "Dorkus", result: "12" },
    { roller: "Dorkus", result: "16" },
    { roller: "Nate", result: "1" },
    { roller: "Nate", result: "18" },
    { roller: "Ellywick 'Stumbleduck' Timbers", result: "14" },
    { roller: "Ellywick 'Stumbleduck' Timbers", result: "15" },
    { roller: "Ellywick 'Stumbleduck' Timbers", result: "15" },
    { roller: "Ellywick 'Stumbleduck' Timbers", result: "8" },
    { roller: "Ellywick 'Stumbleduck' Timbers", result: "14" },
    { roller: "Ellywick 'Stumbleduck' Timbers", result: "18" },
    { roller: "Nate", result: "12" },
    { roller: "Nate", result: "20" },
    { roller: "Ellywick 'Stumbleduck' Timbers", result: "15" },
    { roller: "Ellywick 'Stumbleduck' Timbers", result: "9" },
    { roller: "Dorkus", result: "11" },
    { roller: "Dorkus", result: "4" },
    { roller: "Ellywick 'Stumbleduck' Timbers", result: "12" },
    { roller: "Ellywick 'Stumbleduck' Timbers", result: "9" },
    { roller: "DM (Kevin) (GM)", result: "10" },
    { roller: "Dorkus", result: "9" },
    { roller: "Dorkus", result: "4" },
    { roller: "Dorkus", result: "7" },
    { roller: "Ellywick 'Stumbleduck' Timbers", result: "1" },
    { roller: "Torenx", result: "12" },
    { roller: "DM (Kevin) (GM)", result: "18" },
    { roller: "Torenx", result: "18" },
    { roller: "Torenx", result: "9" },
    { roller: "Dorkus", result: "12" },
    { roller: "Dorkus", result: "20" },
    { roller: "Dorkus", result: "14" },
    { roller: "Dorkus", result: "9" },
    { roller: "Dorkus", result: "17" },
    { roller: "Dorkus", result: "9" },
    { roller: "Dorkus", result: "17" },
    { roller: "Dorkus", result: "14" },
    { roller: "Torenx", result: "20" },
    { roller: "Torenx", result: "3" },
    { roller: "Ellywick 'Stumbleduck' Timbers", result: "13" },
    { roller: "Torenx", result: "13" },
    { roller: "Dorkus", result: "10" },
    { roller: "DM (Kevin) (GM)", result: "7" },
    { roller: "DM (Kevin) (GM)", result: "16" },
    { roller: "DM (Kevin) (GM)", result: "9" },
    { roller: "DM (Kevin) (GM)", result: "3" },
    { roller: "DM (Kevin) (GM)", result: "12" },
    { roller: "DM (Kevin) (GM)", result: "10" },
    { roller: "Ellywick 'Stumbleduck' Timbers", result: "8" },
    { roller: "Ellywick 'Stumbleduck' Timbers", result: "5" },
    { roller: "Dorkus", result: "10" },
    { roller: "Dorkus", result: "20" },
    { roller: "DM (Kevin) (GM)", result: "18" },
    { roller: "DM (Kevin) (GM)", result: "7" },
    { roller: "Ellywick 'Stumbleduck' Timbers", result: "2" },
    { roller: "Ellywick 'Stumbleduck' Timbers", result: "20" },
    { roller: "Torenx", result: "12" },
    { roller: "Torenx", result: "18" },
    { roller: "Dorkus", result: "1" },
    { roller: "Dorkus", result: "18" },
    { roller: "DM (Kevin) (GM)", result: "14" },
    { roller: "DM (Kevin) (GM)", result: "14" },
    { roller: "DM (Kevin) (GM)", result: "11" },
    { roller: "Ellywick 'Stumbleduck' Timbers", result: "14" },
    { roller: "Ellywick 'Stumbleduck' Timbers", result: "16" },
    { roller: "Torenx", result: "2" },
    { roller: "Torenx", result: "3" },
    { roller: "Dorkus", result: "9" },
    { roller: "Dorkus", result: "6" },
    { roller: "DM (Kevin) (GM)", result: "4" },
    { roller: "DM (Kevin) (GM)", result: "4" },
    { roller: "DM (Kevin) (GM)", result: "4" },
    { roller: "Ellywick 'Stumbleduck' Timbers", result: "11" },
    { roller: "Ellywick 'Stumbleduck' Timbers", result: "5" },
    { roller: "Torenx", result: "4" },
    { roller: "Torenx", result: "19" },
    { roller: "Dorkus", result: "9" },
    { roller: "Dorkus", result: "4" },
    { roller: "DM (Kevin) (GM)", result: "15" },
    { roller: "DM (Kevin) (GM)", result: "2" },
    { roller: "Ellywick 'Stumbleduck' Timbers", result: "15" },
    { roller: "Ellywick 'Stumbleduck' Timbers", result: "6" },
    { roller: "Torenx", result: "8" },
    { roller: "Torenx", result: "15" },
    { roller: "Dorkus", result: "15" },
    { roller: "Dorkus", result: "13" },
    { roller: "DM (Kevin) (GM)", result: "20" },
    { roller: "Torenx", result: "20" },
    { roller: "Torenx", result: "1" },
    { roller: "Dorkus", result: "10" },
    { roller: "Dorkus", result: "5" },
    { roller: "Dorkus", result: "10" },
    { roller: "Dorkus", result: "9" },
    { roller: "Dorkus", result: "19" },
    { roller: "Dorkus", result: "6" },
    { roller: "DM (Kevin) (GM)", result: "10" },
    { roller: "Dorkus", result: "3" },
    { roller: "Dorkus", result: "8" },
    { roller: "Torenx", result: "8" },
    { roller: "Ellywick 'Stumbleduck' Timbers", result: "2" },
    { roller: "Dorkus", result: "16" },
    { roller: "DM (Kevin) (GM)", result: "1" },
    { roller: "DM (Kevin) (GM)", result: "5" },
    { roller: "Dorkus", result: "8" },
    { roller: "Dorkus", result: "1" },
    { roller: "Torenx", result: "3" },
    { roller: "Torenx", result: "14" },
    { roller: "DM (Kevin) (GM)", result: "4" },
    { roller: "DM (Kevin) (GM)", result: "8" },
    { roller: "Dorkus", result: "12" },
    { roller: "Dorkus", result: "12" },
    { roller: "Torenx", result: "18" },
    { roller: "Torenx", result: "19" },
    { roller: "Ellywick 'Stumbleduck' Timbers", result: "6" },
    { roller: "Ellywick 'Stumbleduck' Timbers", result: "2" },
    { roller: "Ellywick 'Stumbleduck' Timbers", result: "16" },
    { roller: "Ellywick 'Stumbleduck' Timbers", result: "4" },
    { roller: "Dorkus", result: "6" },
    { roller: "Dorkus", result: "1" },
    { roller: "Torenx", result: "16" },
    { roller: "Torenx", result: "15" },
    { roller: "Ellywick 'Stumbleduck' Timbers", result: "20" },
    { roller: "Ellywick 'Stumbleduck' Timbers", result: "16" },
    { roller: "Dorkus", result: "6" },
    { roller: "Dorkus", result: "8" },
  ],
  playerNames: ["DM (Kevin) (GM)", "Nate", "Dorkus", "Ellywick 'Stumbleduck' Timbers", "Torenx"]
};