export const mockRollerNameDM = 'DM (Kevin) (GM)';
export const mockRollerNameNate = 'Nate';
export const mockRollerNameDorkus = 'Dorkus';
export const mockRollerNameEllywick = 'Ellywick \'Stumbleduck\' Timbers';
export const mockRollerNameTorenx = 'Torenx';

export const mockRollData = {
  d20Rolls: [
    { roller: mockRollerNameDM, result: "4" },
    { roller: mockRollerNameNate, result: "12" },
    { roller: mockRollerNameNate, result: "15" },
    { roller: mockRollerNameNate, result: "14" },
    { roller: mockRollerNameNate, result: "7" },
    { roller: mockRollerNameNate, result: "8" },
    { roller: mockRollerNameNate, result: "2" },
    { roller: mockRollerNameDorkus, result: "20" },
    { roller: mockRollerNameDorkus, result: "19" },
    { roller: mockRollerNameNate, result: "2" },
    { roller: mockRollerNameNate, result: "11" },
    { roller: mockRollerNameNate, result: "18" },
    { roller: mockRollerNameNate, result: "14" },
    { roller: mockRollerNameDorkus, result: "12" },
    { roller: mockRollerNameDorkus, result: "16" },
    { roller: mockRollerNameNate, result: "1" },
    { roller: mockRollerNameNate, result: "18" },
    { roller: mockRollerNameEllywick, result: "14" },
    { roller: mockRollerNameEllywick, result: "15" },
    { roller: mockRollerNameEllywick, result: "15" },
    { roller: mockRollerNameEllywick, result: "8" },
    { roller: mockRollerNameEllywick, result: "14" },
    { roller: mockRollerNameEllywick, result: "18" },
    { roller: mockRollerNameNate, result: "12" },
    { roller: mockRollerNameNate, result: "20" },
    { roller: mockRollerNameEllywick, result: "15" },
    { roller: mockRollerNameEllywick, result: "9" },
    { roller: mockRollerNameDorkus, result: "11" },
    { roller: mockRollerNameDorkus, result: "4" },
    { roller: mockRollerNameEllywick, result: "12" },
    { roller: mockRollerNameEllywick, result: "9" },
    { roller: mockRollerNameDM, result: "10" },
    { roller: mockRollerNameDorkus, result: "9" },
    { roller: mockRollerNameDorkus, result: "4" },
    { roller: mockRollerNameDorkus, result: "7" },
    { roller: mockRollerNameEllywick, result: "1" },
    { roller: mockRollerNameTorenx, result: "12" },
    { roller: mockRollerNameDM, result: "18" },
    { roller: mockRollerNameTorenx, result: "18" },
    { roller: mockRollerNameTorenx, result: "9" },
    { roller: mockRollerNameDorkus, result: "12" },
    { roller: mockRollerNameDorkus, result: "20" },
    { roller: mockRollerNameDorkus, result: "14" },
    { roller: mockRollerNameDorkus, result: "9" },
    { roller: mockRollerNameDorkus, result: "17" },
    { roller: mockRollerNameDorkus, result: "9" },
    { roller: mockRollerNameDorkus, result: "17" },
    { roller: mockRollerNameDorkus, result: "14" },
    { roller: mockRollerNameTorenx, result: "20" },
    { roller: mockRollerNameTorenx, result: "3" },
    { roller: mockRollerNameEllywick, result: "13" },
    { roller: mockRollerNameTorenx, result: "13" },
    { roller: mockRollerNameDorkus, result: "10" },
    { roller: mockRollerNameDM, result: "7" },
    { roller: mockRollerNameDM, result: "16" },
    { roller: mockRollerNameDM, result: "9" },
    { roller: mockRollerNameDM, result: "3" },
    { roller: mockRollerNameDM, result: "12" },
    { roller: mockRollerNameDM, result: "10" },
    { roller: mockRollerNameEllywick, result: "8" },
    { roller: mockRollerNameEllywick, result: "5" },
    { roller: mockRollerNameDorkus, result: "10" },
    { roller: mockRollerNameDorkus, result: "20" },
    { roller: mockRollerNameDM, result: "18" },
    { roller: mockRollerNameDM, result: "7" },
    { roller: mockRollerNameEllywick, result: "2" },
    { roller: mockRollerNameEllywick, result: "20" },
    { roller: mockRollerNameTorenx, result: "12" },
    { roller: mockRollerNameTorenx, result: "18" },
    { roller: mockRollerNameDorkus, result: "1" },
    { roller: mockRollerNameDorkus, result: "18" },
    { roller: mockRollerNameDM, result: "14" },
    { roller: mockRollerNameDM, result: "14" },
    { roller: mockRollerNameDM, result: "11" },
    { roller: mockRollerNameEllywick, result: "14" },
    { roller: mockRollerNameEllywick, result: "16" },
    { roller: mockRollerNameTorenx, result: "2" },
    { roller: mockRollerNameTorenx, result: "3" },
    { roller: mockRollerNameDorkus, result: "9" },
    { roller: mockRollerNameDorkus, result: "6" },
    { roller: mockRollerNameDM, result: "4" },
    { roller: mockRollerNameDM, result: "4" },
    { roller: mockRollerNameDM, result: "4" },
    { roller: mockRollerNameEllywick, result: "11" },
    { roller: mockRollerNameEllywick, result: "5" },
    { roller: mockRollerNameTorenx, result: "4" },
    { roller: mockRollerNameTorenx, result: "19" },
    { roller: mockRollerNameDorkus, result: "9" },
    { roller: mockRollerNameDorkus, result: "4" },
    { roller: mockRollerNameDM, result: "15" },
    { roller: mockRollerNameDM, result: "2" },
    { roller: mockRollerNameEllywick, result: "15" },
    { roller: mockRollerNameEllywick, result: "6" },
    { roller: mockRollerNameTorenx, result: "8" },
    { roller: mockRollerNameTorenx, result: "15" },
    { roller: mockRollerNameDorkus, result: "15" },
    { roller: mockRollerNameDorkus, result: "13" },
    { roller: mockRollerNameDM, result: "20" },
    { roller: mockRollerNameTorenx, result: "20" },
    { roller: mockRollerNameTorenx, result: "1" },
    { roller: mockRollerNameDorkus, result: "10" },
    { roller: mockRollerNameDorkus, result: "5" },
    { roller: mockRollerNameDorkus, result: "10" },
    { roller: mockRollerNameDorkus, result: "9" },
    { roller: mockRollerNameDorkus, result: "19" },
    { roller: mockRollerNameDorkus, result: "6" },
    { roller: mockRollerNameDM, result: "10" },
    { roller: mockRollerNameDorkus, result: "3" },
    { roller: mockRollerNameDorkus, result: "8" },
    { roller: mockRollerNameTorenx, result: "8" },
    { roller: mockRollerNameEllywick, result: "2" },
    { roller: mockRollerNameDorkus, result: "16" },
    { roller: mockRollerNameDM, result: "1" },
    { roller: mockRollerNameDM, result: "5" },
    { roller: mockRollerNameDorkus, result: "8" },
    { roller: mockRollerNameDorkus, result: "1" },
    { roller: mockRollerNameTorenx, result: "3" },
    { roller: mockRollerNameTorenx, result: "14" },
    { roller: mockRollerNameDM, result: "4" },
    { roller: mockRollerNameDM, result: "8" },
    { roller: mockRollerNameDorkus, result: "12" },
    { roller: mockRollerNameDorkus, result: "12" },
    { roller: mockRollerNameTorenx, result: "18" },
    { roller: mockRollerNameTorenx, result: "19" },
    { roller: mockRollerNameEllywick, result: "6" },
    { roller: mockRollerNameEllywick, result: "2" },
    { roller: mockRollerNameEllywick, result: "16" },
    { roller: mockRollerNameEllywick, result: "4" },
    { roller: mockRollerNameDorkus, result: "6" },
    { roller: mockRollerNameDorkus, result: "1" },
    { roller: mockRollerNameTorenx, result: "16" },
    { roller: mockRollerNameTorenx, result: "15" },
    { roller: mockRollerNameEllywick, result: "20" },
    { roller: mockRollerNameEllywick, result: "16" },
    { roller: mockRollerNameDorkus, result: "6" },
    { roller: mockRollerNameDorkus, result: "8" },
  ],
  playerNames: [
    mockRollerNameDM,
    mockRollerNameNate,
    mockRollerNameDorkus,
    mockRollerNameEllywick,
    mockRollerNameTorenx
  ]
};